[package]
name = "cyclone-physics-rs"
version = "0.1.0"
authors = ["Rutvik <heyrutvik@gmail.com>"]
edition = "2021"

[lib]
name = "cyclone"
path = "src/cyclone/lib.rs"

[dependencies]
kiss3d = "0.30"
nalgebra = "0.31.3"
rand = "0.8.5"